USE ecom;

-- SELECT * FROM order_details;

-- SELECT COUNT(*) FROM order_details;    -- shows number of columns... 

-- SELECT SUM(quantity * price_per_unit) AS total_revenue FROM order_details;        -- use to calculate sum...

-- SELECT AVG(price_per_unit) AS avg_orders FROM order_details;          -- to calculate average...

-- SELECT MIN(price_per_unit) AS min_price, MAX(price_per_unit) AS max_price FROM order_details;    -- to calculate minimum and maximum...

-- SELECT customer_name AS n, ROUND(price_per_unit, 0) AS p FROM order_details;      -- to remove decimals...

-- SELECT UPPER(customer_name), LOWER(city) FROM order_details;                -- to convert text into uppercase and lowercase...

-- SELECT customer_name, LENGTH(customer_name) FROM order_details;              -- to check the number of characters...

-- SELECT CURRENT_DATE;         -- to show current date...

-- SELECT CURRENT_TIME;         -- to show current time...

-- SELECT CURRENT_TIMESTAMP;    -- to show current date and time...

-- SELECT order_id, DATEDIFF(delivery_date, order_date) AS delivery_days FROM order_details;     --  to calculate difference between two dates...

SELECT * FROM order_details WHERE YEAR(order_date) = 2025;            -- to get order details on the basis of order date...